#!/usr/bin/env bash
# Build script to generate standalone install/uninstall scripts
set -e

SCRIPT_DIR="$(dirname "$0")"
COMMON_FILE="$SCRIPT_DIR/common.sh"
SRC_INSTALL="$SCRIPT_DIR/install.src.sh"
SRC_UNINSTALL="$SCRIPT_DIR/uninstall.src.sh"
OUT_INSTALL="$SCRIPT_DIR/../install.sh"
OUT_UNINSTALL="$SCRIPT_DIR/../uninstall.sh"

echo "Building standalone scripts..."

# Function to build a standalone script
build_script() {
    local src_file="$1"
    local out_file="$2"
    local script_name="$(basename "$out_file")"
    
    # echo "Building $script_name..."
    
    # Start with shebang and comment
    cat > "$out_file" << 'EOF'
#!/usr/bin/env bash
# This file is auto-generated by scripts/build.sh
# DO NOT EDIT - modify scripts/*.src.sh instead and run 'make buildscripts'
EOF
    
    # Process the source file line by line
    while IFS= read -r line; do
        # Skip the shebang in source file
        if [[ "$line" =~ ^#!/.* ]]; then
            continue
        fi
       
        # Replace the common.sh source line with actual content
        if [[ "$line" =~ source.*common\.sh ]]; then
            echo "# ── Inlined content from common.sh ──────────────────────────────────────────" >> "$out_file"
            tail -n +2 "$COMMON_FILE" | grep -v '^#.*Common configuration' >> "$out_file"
            echo "# ── End of inlined content ──────────────────────────────────────────────────" >> "$out_file"
        else
            echo "$line" >> "$out_file"
        fi
    done < "$src_file"
    
    # Make executable
    chmod +x "$out_file"
    echo "✓ Generated $out_file"
}

# Build both scripts
build_script "$SRC_INSTALL" "$OUT_INSTALL"
build_script "$SRC_UNINSTALL" "$OUT_UNINSTALL"

echo "✓ Build complete!" 